### ISSUE TITLE
gulp watch and gulp dev don't generate assets.php file

### ISSUE THREAD

**Issue by alexdelgado** [moderntribe/square-one#636] opened 2020-09-22 15:52 UTC
If you run `gulp watch` or `gulp watch` without having previously run `gulp` or `gulp dist` the `assets.php` file won't be generated so assets won't be enqueued. 

If you run `gulp dev` in the theme, the first time (without an existing assets.php file), that appears to cause a webpack error because assets.php is missing.

**Comment by alexdelgado** [comment] 2020-09-22 15:54
It seems like the "happy path" is to add `define( 'SCRIPT_DEBUG', true );` and `define( 'ASSET_VERSION_TIMESTAMP', true );` to your `local-config.php` file then run `gulp` or `gulp dist` and then `gulp watch` or `gulp watch`.

I think it would be helpful if `gulp watch` and `gulp watch` generated the `assets.php` file so you're not necessarily dependent on running `gulp` or `gulp dist` and having the correct PHP Definitions.

**Comment by alexdelgado** [comment] 2020-09-22 15:55
We may also need to look at the documentation to make sure the process is properly documented.

**Comment by faction23** [comment] 2021-06-05 23:29
This is by design, generating the asset file on every single watch run slows down watch too much and isnt really needed. This timestamp approach when script debug is true is the same technique used by WordPress core on Gutenberg and other modern libs they are building, so it is a common pattern. I'll close this out, thanks Alex!

**Closed by faction23** 2021-06-05 23:29 UTC
Labels: bug
